### ISSUE TITLE
Uncaught TypeError: Cannot read property 'methods' of undefined

### ISSUE THREAD

**Issue by Stardidi** [jacknbeans/hexe#1]
[Enter steps to reproduce:]

1. Type something that is not a HexEngine method table.
2. Type '.'.
3. Get error
For example:
```
local bla
bla.
```

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [hexe](https://github.com/jacknbeans/hexe) package 0.2.1

### Stack Trace

Uncaught TypeError: Cannot read property 'methods' of undefined

```
At C:\Users\david\.atom\packages\hexe\lib\hexe_autocomplete.js:99

TypeError: Cannot read property 'methods' of undefined
    at /packages/hexe/lib/hexe_autocomplete.js:99:55
    at Object.getSuggestions (/packages/hexe/lib/hexe_autocomplete.js:110:71)
    at /app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:333:54
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:309:17)
    at AutocompleteManager.findSuggestions (/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:298:19)
```

### Commands

```
     -1:57.5.0 editor:indent (input.hidden-input)
 14x -1:49.5.0 core:move-down (input.hidden-input)
  2x -1:48.2.0 core:move-up (input.hidden-input)
  3x -1:47.6.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -1:40.9.0 autocomplete-plus:confirm (input.hidden-input)
     -1:40 core:undo (input.hidden-input)
     -1:39.6.0 autocomplete-plus:activate (input.hidden-input)
  2x -1:05.9.0 core:page-down (input.hidden-input)
 20x -0:45.8.0 core:move-up (input.hidden-input)
  2x -0:42.3.0 core:move-down (input.hidden-input)
  3x -0:29.5.0 core:move-up (input.hidden-input)
  4x -0:28.5.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -0:25.5.0 autocomplete-plus:activate (input.hidden-input)
  3x -0:22.9.0 core:backspace (input.hidden-input)
     -0:18.9.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -0:17.6.0 autocomplete-plus:confirm (input.hidden-input)
```

### Non-Core Packages

```
asciidoc-preview 2.9.0 
atom-perforce 1.7.9 
hexe 0.2.1 
language-lua 0.9.11 
```

**Comment by jacknbeans** [comment]
Fixed with [commit](https://github.com/jacknbeans/hexe/commit/26b1f2e5df5becea924f23e6a3b1ab169dc99041). Wasn't checking whether or not the value before the period was a valid script bind. Am now doing so.
