### ISSUE TITLE
Failed to activate the hexe package

### ISSUE THREAD

**Issue by Stardidi** [jacknbeans/hexe#2]
[Enter steps to reproduce:]

1. install package
2. open atom

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [hexe](https://github.com/jacknbeans/hexe) package 0.3.0

### Stack Trace

Failed to activate the hexe package

```
At Cannot set property 'emitter' of undefined

TypeError: Cannot set property 'emitter' of undefined
  at /packages/hexe/lib/hexe.js:59:31)
  at Object.activate (/packages/hexe/lib/hexe.js:137:21)
  at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
  at /app.asar/src/package.js:190:32
  at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
  at /app.asar/src/package.js:183:26
  at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
  at /app.asar/src/package-manager.js:531:29
  at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
  at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
  at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
  at /app.asar/src/atom-environment.js:812:28

```

### Commands

```
```

### Non-Core Packages

```
asciidoc-preview 2.9.1 
atom-perforce 1.7.9 
hexe 0.3.0 
```

**Comment by jacknbeans** [comment]
Fixed with commit https://github.com/jacknbeans/hexe/commit/e7c55e723ffa4f0b48fbfd11c00dee7e3871eb90
