### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Stardidi** [jacknbeans/hexe#3]
[Enter steps to reproduce:]

1. Type any character

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [hexe](https://github.com/jacknbeans/hexe) package 0.3.3

### Stack Trace

Uncaught TypeError: Cannot convert undefined or null to object

```
At C:\Users\david\.atom\packages\hexe\lib\hexe_autocomplete.js:114

TypeError: Cannot convert undefined or null to object
    at /packages/hexe/lib/hexe_autocomplete.js:114:21
    at Object.getSuggestions (/packages/hexe/lib/hexe_autocomplete.js:116:71)
    at /app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:333:54
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:309:17)
    at AutocompleteManager.findSuggestions (/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:298:19)
```

### Commands

```
     -0:43.9.0 core:close (div.panels-item)
     -0:30.6.0 command-palette:toggle (input.hidden-input)
     -0:29 core:confirm (input.hidden-input)
     -0:29 pane:close (input.hidden-input)
  4x -0:19.2.0 core:undo (input.hidden-input)
```

### Non-Core Packages

```
asciidoc-preview 2.10.0 
atom-perforce 1.7.9 
hexe 0.3.3 
language-lua 0.9.11 
```

**Comment by jacknbeans** [comment]
@Stardidi this is a very strange error, it's as if you don't have the scriptbinds.json file on your computer. Can you confirm for me that you do?

**Comment by Stardidi** [comment]
I do have that file at:
documentation\doxygen\output\json\scriptbinds.json

**Comment by jacknbeans** [comment]
Hmm okay, I'll check it out.

**Comment by jacknbeans** [comment]
Should be fixed (https://github.com/jacknbeans/hexe/commit/609e385486c8b1ecf806e1473ebe15e17bfa0e9d)
