### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scriptbinds' of null

### ISSUE THREAD

**Issue by Stardidi** [jacknbeans/hexe#4]
[Enter steps to reproduce:]

1. Type a character in a lua file

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [hexe](https://github.com/jacknbeans/hexe) package 0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'scriptbinds' of null

```
At C:\Users\david\.atom\packages\hexe\lib\hexe_autocomplete.js:114

TypeError: Cannot read property 'scriptbinds' of null
    at /packages/hexe/lib/hexe_autocomplete.js:114:30
    at Object.getSuggestions (/packages/hexe/lib/hexe_autocomplete.js:116:71)
    at /app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:333:54
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:309:17)
    at AutocompleteManager.findSuggestions (/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:298:19)
```

### Commands

```
     -1:01.4.0 application:open-folder (div.package-detail.panels-item)
     -0:58.7.0 application:add-project-folder (div.package-detail.panels-item)
     -0:53.9.0 snippets:next-tab-stop (input.hidden-input)
     -0:53.9.0 snippets:expand (input.hidden-input)
     -0:53.9.0 editor:indent (input.hidden-input)
  2x -0:50.7.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -0:45.7.0 hexe:help (input.hidden-input)
     -0:30.4.0 core:move-up (input.hidden-input)
     -0:30.2.0 editor:newline (input.hidden-input)
     -0:25.1.0 core:move-up (input.hidden-input)
     -0:24.9.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:21.4.0 core:move-up (input.hidden-input)
     -0:21.1.0 editor:newline (input.hidden-input)
  3x -0:16.4.0 editor:delete-to-beginning-of-word (input.hidden-input)
```

### Non-Core Packages

```
asciidoc-preview 2.10.0 
atom-perforce 1.7.9 
hexe 0.4.0 
language-lua 0.9.11 
```

**Comment by jacknbeans** [comment]
Should be fixed (https://github.com/jacknbeans/hexe/commit/609e385486c8b1ecf806e1473ebe15e17bfa0e9d)
