### ISSUE TITLE
Uncaught TypeError: Cannot read property 'hasOwnProperty' of null

### ISSUE THREAD

**Issue by Stardidi** [jacknbeans/hexe#6]
[Enter steps to reproduce:]

1. Freshly install atom
2. create a Lua file
(3. Start a comment block: ``` -- ```)

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [hexe](https://github.com/jacknbeans/hexe) package 0.4.3

### Stack Trace

Uncaught TypeError: Cannot read property 'hasOwnProperty' of null

```
At C:\Users\david\.atom\packages\hexe\lib\hexe_autocomplete.js:114

TypeError: Cannot read property 'hasOwnProperty' of null
    at /packages/hexe/lib/hexe_autocomplete.js:114:16
    at Object.getSuggestions (/packages/hexe/lib/hexe_autocomplete.js:118:71)
    at /app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:333:54
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:309:17)
    at AutocompleteManager.findSuggestions (/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:298:19)
```

### Commands

```
     -1:08.3.0 core:backspace (input.hidden-input)
  4x -1:07.7.0 core:move-up (input.hidden-input)
     -1:07.0 core:move-right (input.hidden-input)
  3x -1:06.8.0 editor:move-to-end-of-word (input.hidden-input)
     -1:05.2.0 core:save (input.hidden-input)
     -0:59.1.0 core:move-to-top (input.hidden-input)
     -0:50.9.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:43.8.0 pane:show-previous-item (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:20.8.0 core:select-all (input.hidden-input)
     -0:20.5.0 core:copy (input.hidden-input)
  2x -0:19.9.0 editor:move-line-up (input.hidden-input)
  2x -0:19.1.0 core:move-up (input.hidden-input)
     -0:16.5.0 editor:newline (input.hidden-input)
     -0:16.1.0 core:move-up (input.hidden-input)
     -0:15.5.0 core:paste (input.hidden-input)
     -0:00.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
asciidoc-preview 2.10.1 
hexe 0.4.3 
language-asciidoc 1.10.0 
language-lua 0.9.11 
```

**Comment by jacknbeans** [comment]
I believe this is caused by the fact that the default location of where the package is looking for the scriptbinds.json file is incorrect. Once we have a setup for where the build is going to be put, I can put the scriptbinds.json file beside the binary (or in its own docs subfolder, if preferred).

**Comment by jacknbeans** [comment]
With commit 8a3c9847c31b4cfed0a96f390b26c6afd57ba6c2 I added an extra check that should take care of this and it will also have an error pop up with a tip of how to fix the error.
