### ISSUE TITLE
Uncaught TypeError: v.params[Symbol.iterator] is not a function

### ISSUE THREAD

**Issue by Stardidi** [jacknbeans/hexe#7]
[Enter steps to reproduce:]

1. Type any scriptbind name and hit '.' So for example: ```Tokens.```
2. Get error and no further suggestions

The scriptbinds json is set correctly, and the Tile/Tokens/Prefabs suggestions show up properly

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [hexe](https://github.com/jacknbeans/hexe) package 0.5.5

### Stack Trace

Uncaught TypeError: v.params[Symbol.iterator] is not a function

```
At C:\Users\david\.atom\packages\hexe\lib\hexe_autocomplete.js:27

TypeError: v.params[Symbol.iterator] is not a function
    at formatAutoComplete (/packages/hexe/lib/hexe_autocomplete.js:27:20)
    at /packages/hexe/lib/hexe_autocomplete.js:112:23
    at Array.map (native)
    at /packages/hexe/lib/hexe_autocomplete.js:112:14
    at Object.getSuggestions (/packages/hexe/lib/hexe_autocomplete.js:136:71)
    at ~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:1
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:1)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:1)
```

### Commands

```
     -0:07.1.0 core:backspace (input.hidden-input)
  2x -0:06.8.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
asciidoc-preview 2.10.1 
autocomplete-glsl 0.2.3 
hexe 0.5.5 
language-asciidoc 1.10.0 
language-glsl 2.0.1 
language-lua 0.9.11 
```

**Comment by jacknbeans** [comment]
The issue was resolved in person. Reason to the problem wasn't found, restarting Atom fixed it.
